-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base
import Circe.Emit.M2Fwd

/-- Pure translation of `_ZN3Acc3addEi` (mutating `add`: checked field addition). -/
def _ZN3Acc3addEi_fwd (s v : BitVec 32) : Result (BitVec 32) :=
  accAdd s v
