-- Generated by the Circe emitter (Phase 3) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add` / `emit_correct_incr`):
-- this file is the tag-erased rendering of the verified forward function
-- (`Value.i32` tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase3.sh`.

import Circe.Base

/-- Pure translation of `add`: values in, value out (no memory). -/
def add_fwd (a b : BitVec 32) : Result (BitVec 32) :=
  checkedAddI32 a b
