-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_Z3addiii` (3-`i32` overload leaf: two threaded `nsw` adds). -/
def _Z3addiii_fwd (x y z : BitVec 32) : Result (BitVec 32) :=
  do let t ← checkedAddI32 x y
     checkedAddI32 t z
