-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `add_caller` (DAG calls into `add_fwd`, twice;
    leaf body `checkedAddI32` inlined, see `addCallerFwd_as_calls`). -/
def add_caller_fwd (x y z : BitVec 32) : Result (BitVec 32) :=
  do let t ← checkedAddI32 x y
     checkedAddI32 t z
