-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_Z9array_sumRKSt5arrayIiLm4EE` (4 reads through `operator[]`, three threaded `nsw` adds). -/
def _Z9array_sumRKSt5arrayIiLm4EE_fwd (a b c d : BitVec 32) : Result (BitVec 32) :=
  do let t ← checkedAddI32 a b
     let u ← checkedAddI32 t c
     checkedAddI32 u d
