-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNSt14__array_traitsIjLm4EE6_S_refERA4_Kjm` (unchecked `u64` index into the 4-word `u32` array). -/
def _ZNSt14__array_traitsIjLm4EE6_S_refERA4_Kjm_fwd (t : List (BitVec 32)) (n : BitVec 64) : Result (BitVec 32) :=
  match t[n.toNat]? with
  | some x => .ok x
  | none => .error .OOB
