-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_Z14array_sort_sumv` (sort `[3, 1, 2, 0]`, three wrapping adds). -/
def _Z14array_sort_sumv_insert (x : BitVec 32) : List (BitVec 32) → List (BitVec 32)
  | [] => [x]
  | y :: ys => if x.ult y then x :: y :: ys else y :: _Z14array_sort_sumv_insert x ys
def _Z14array_sort_sumv_sort : List (BitVec 32) → List (BitVec 32)
  | [] => []
  | x :: xs => _Z14array_sort_sumv_insert x (_Z14array_sort_sumv_sort xs)
def _Z14array_sort_sumv_fwd : Result (BitVec 32) :=
  .ok (((_Z14array_sort_sumv_sort [3, 1, 2, 0]).foldl (· + ·) 0))
