-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base
import Circe.Crypto.Block

/-- Pure translation of `chacha20_block`: 16-word state in, blocked state out. -/
def chacha20_block_fwd (s : List (BitVec 32)) : Result (List (BitVec 32)) :=
  if 16 ≤ s.length then
    .ok (addBackList s (chachaRounds 10 s) 16)
  else .error .OOB
