-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `choose` (borrow-return): forward selection. -/
def choose_fwd (b : Bool) (x y : BitVec 32) : Result (BitVec 32) :=
  .ok (if b then x else y)

/-- Backward propagation for `choose`: the updated return value flows back to the selected input; the other input is unchanged. -/
def choose_back (b : Bool) (x y ret : BitVec 32) : Result (BitVec 32 × BitVec 32) :=
  .ok (if b then (ret, y) else (x, ret))
