-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `cls_break` (break-`switch` without default, value-level). -/
def cls_break_fwd (x : BitVec 32) : Result (BitVec 32) :=
  .ok (if x == 0 then 10 else if x == 1 then 20 else 99)
