-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `cls_dense` (dense `switch`, lowered to an if-chain). -/
def cls_dense_fwd (x : BitVec 32) : Result (BitVec 32) :=
  if x == 0 then .ok 0
  else if x == 1 then .ok 10
  else if x == 2 then .ok 20
  else if x == 3 then .ok 30
  else if x == 4 then .ok 40
  else if x == 5 then .ok 50
  else if x == 6 then .ok 60
  else if x == 7 then .ok 70
  else .ok 80
