-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `find_eq` (bounded search with early return). -/
def find_eq_fwd (a : List (BitVec 32)) (n k : BitVec 32) : Result (BitVec 32) :=
  findEqOut a n.toNat k
