-- Generated by the Circe emitter (Phase 3) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add` / `emit_correct_incr`):
-- this file is the tag-erased rendering of the verified forward function
-- (`Value.i32` tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase3.sh`.

import Circe.Base

/-- Pure translation of `incr` (`*p = *p + 1`, functionalized).
    Caller rewrite: `incr(&y)` becomes `y ← incr_fwd y`. -/
def incr_fwd (p : BitVec 32) : Result (BitVec 32) :=
  checkedIncrI32 p
