-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_Z15insertion_sort8RSt5arrayIjLm8EE` (insertion sort over the 8-word `u32` array). -/
def _Z15insertion_sort8RSt5arrayIjLm8EE_insert (x : BitVec 32) : List (BitVec 32) → List (BitVec 32)
  | [] => [x]
  | y :: ys => if x.ult y then x :: y :: ys else y :: _Z15insertion_sort8RSt5arrayIjLm8EE_insert x ys
def _Z15insertion_sort8RSt5arrayIjLm8EE_sort : List (BitVec 32) → List (BitVec 32)
  | [] => []
  | x :: xs => _Z15insertion_sort8RSt5arrayIjLm8EE_insert x (_Z15insertion_sort8RSt5arrayIjLm8EE_sort xs)
def _Z15insertion_sort8RSt5arrayIjLm8EE_fwd (a : List (BitVec 32)) : Result (List (BitVec 32)) :=
  .ok (_Z15insertion_sort8RSt5arrayIjLm8EE_sort a)
