-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `nested_sum` (nested bounded `u32` loops, wrapping). -/
def nested_sum_fwd (n m : BitVec 32) : Result (BitVec 32) :=
  .ok (nestedSumU32 n.toNat m.toNat)
