-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNKSt22_Optional_payload_baseIiE6_M_getEv` (the `_M_value` word load; disengaged is `AssertFail`). -/
def _ZNKSt22_Optional_payload_baseIiE6_M_getEv_fwd (o : Option (BitVec 32)) : Result (BitVec 32) :=
  match o with
  | some x => .ok x
  | none => .error .AssertFail
