-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNKSt8optionalIiE9has_valueEv` (delegates to the `_M_is_engaged` bit body). -/
def _ZNKSt8optionalIiE9has_valueEv_fwd (o : Option (BitVec 32)) : Bool :=
  o.isSome
