-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `skip_sum` (bounded loop with `break`/`continue`, wrapping). -/
def skip_sum_fwd (n : BitVec 32) : Result (BitVec 32) :=
  .ok (skipSumU32 n.toNat)
