-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNKSt4spanIKiLm18446744073709551615EE4sizeEv` (delegates to the `_M_extent` length body). -/
def _ZNKSt4spanIKiLm18446744073709551615EE4sizeEv_fwd (l : List (BitVec 32)) : BitVec 64 :=
  BitVec.ofNat 64 l.length
