-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_Z8span_sumSt4spanIKiLm18446744073709551615EE` (index-sum over the reified words; `nsw` overflow is loud). -/
def _Z8span_sumSt4spanIKiLm18446744073709551615EE_fwd (l : List (BitVec 32)) : Result (BitVec 32) :=
  go l 0
where go : List (BitVec 32) → BitVec 32 → Result (BitVec 32)
  | [], acc => .ok acc
  | x :: xs, acc => do
      let a ← checkedAddI32 acc x
      go xs a
