-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNKSt4spanIKiLm18446744073709551615EEixEm` (the fused `operator[]` word read; `OOB` off the end). -/
def _ZNKSt4spanIKiLm18446744073709551615EEixEm_fwd (l : List (BitVec 32)) (n : BitVec 64) : Result (BitVec 32) :=
  match l[n.toNat]? with
  | some x => .ok x
  | none => .error .OOB
