-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `sum_array` (bounded `u32` accumulation, wrapping). -/
def sum_array_fwd {n : Nat} (a : BoundedList (BitVec 32) n) : Result (BitVec 32) :=
  .ok (prefixSumU32 a.val a.val.length)
