-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_Z10use_ns_addii` (delegates to the `_ZN2ns3addEii` namespaced body). -/
def _Z10use_ns_addii_fwd (x y : BitVec 32) : Result (BitVec 32) :=
  checkedAddI32 x y
