-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `vec_alloc` (uniquely-owned `u32` heap block: allocate, fill with indices, sum, free). -/
def vec_alloc_fwd (n : BitVec 32) : Result (BitVec 32) :=
  vecFillSumU32 n.toNat
