-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base
import Circe.Emit.VecFwd

/-- Pure translation of `vec_copy_sum` (two live `u32` heap blocks: allocate two, fill `a` with indices, copy `a` into `b`, sum `b`, free both). -/
def vec_copy_sum_fwd (n : BitVec 32) : Result (BitVec 32) :=
  vecFillSumU32 n.toNat
