-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNSt12_Vector_baseIiSaIiEE13_M_deallocateEPim` (the `ptr_to_bool` guard as the `n == 0` test). -/
def _ZNSt12_Vector_baseIiSaIiEE13_M_deallocateEPim_fwd (b : Vec32) (len cap : Nat) (n : BitVec 64) : Result (Vec32 × Nat × Nat) :=
  if (BitVec.ofNat 64 0).ult n then
    match vecFree b with
    | .error e => .error e
    | .ok b' => .ok (b', len, cap)
  else .ok (b, len, cap)
