-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base
import Circe.Emit.VecGrow
import Circe.Emit.VecCompose

/-- Pure translation of `_ZNSt6vectorIiSaIiEE9push_backEOi` (single-`callProg` forwarder into the proved `emplace_back` composer). -/
def _ZNSt6vectorIiSaIiEE9push_backEOi_fwd (b : Vec32) (len cap : Nat) (x : BitVec 32) : Result Value :=
  stdVecPushBackFwd b len cap x
