-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNSt6vectorIiSaIiEED2Ev` (the `0 < cap`-guarded consume; the destroy range is a no-op for `int`). -/
def _ZNSt6vectorIiSaIiEED2Ev_fwd (b : Vec32) (len cap : Nat) : Result (Vec32 × Nat × Nat) :=
  if 0 < cap then
    match vecFree b with
    | .error e => .error e
    | .ok b' => .ok (b', len, cap)
  else .ok (b, len, cap)
