-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNSt6vectorIiSaIiEE11_S_relocateEPiS2_S2_RS0_` (the copy loop over the destination triple; the source triple is unchanged). -/
def _ZNSt6vectorIiSaIiEE11_S_relocateEPiS2_S2_RS0__fwd (bS : Vec32) (lenS : Nat) (_capS : Nat) (bD : Vec32) (lenD capD : Nat) (first last result : BitVec 64) : Result (Vec32 × Nat × Nat) :=
  match stdVecBlitFold bS.val lenS bS.freed bD result.toNat first.toNat (last.toNat - first.toNat) with
  | .error e => .error e
  | .ok bD' => .ok (bD', lenD, capD)
