-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZSt8_DestroyIPiiEvT_S1_RSaIT0_E` (the trivial-`int` destroy range: nothing destroyed). -/
def _ZSt8_DestroyIPiiEvT_S1_RSaIT0_E_fwd (_a _b : BitVec 64) : BitVec 32 :=
  BitVec.ofNat 32 0
