-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNSt12_Vector_baseIiSaIiEE11_M_allocateEm` (fresh storage like `boxNew`; the over-max throw pair fuses to `fail`). -/
def _ZNSt12_Vector_baseIiSaIiEE11_M_allocateEm_fwd (n : BitVec 64) : Result (Vec32 × Nat × Nat) :=
  if (BitVec.ofNat 64 0).ult n then
    if (BitVec.ofNat 64 2305843009213693951).ult n then .error .AssertFail
    else .ok (⟨List.replicate n.toNat 0, false⟩, 0, n.toNat)
  else .ok (⟨[], false⟩, 0, 0)
