-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNK9__gnu_cxx13new_allocatorIiE11_M_max_sizeEv` (the max-size chain folds to `diffmax`). -/
def _ZNK9__gnu_cxx13new_allocatorIiE11_M_max_sizeEv_fwd : BitVec 64 :=
  BitVec.ofNat 64 2305843009213693951
