-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base
import Circe.Emit.VecGrow
import Circe.Emit.VecCompose

/-- Pure translation of `_ZNSt6vectorIiSaIiEE7reserveEm` (the guarded composition over the frozen leaf forwards). -/
def _ZNSt6vectorIiSaIiEE7reserveEm_fwd (b : Vec32) (len cap : Nat) (n : BitVec 64) : Result Value :=
  if stdVecMaxDiffBV.ult n then .error .AssertFail
  else if (BitVec.ofNat 64 cap).ult n then
    (stdVecAllocFwd n).bind fun alv =>
    (vecGrowOwned alv).bind fun (bNew, lenA, capA) =>
    (stdVecRelocFwd b len cap bNew lenA capA (BitVec.ofNat 64 0)
      (BitVec.ofNat 64 len) (BitVec.ofNat 64 0)).bind fun rlv =>
    (vecGrowOwned rlv).bind fun (bR, _lenR, capR) =>
    (stdVecDeallocGuardFwd b len cap
      (BitVec.ofNat 64 cap)).bind fun _ =>
    .ok (.stdVecOwned bR ((BitVec.ofNat 64 len).toNat) capR)
  else .ok (.stdVecOwned b len cap)
