-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNSt16allocator_traitsISaIiEE9constructIiJiEEEvRS0_PT_DpOT0_` (placement store of the `i32` word at the `u64` offset). -/
def _ZNSt16allocator_traitsISaIiEE9constructIiJiEEEvRS0_PT_DpOT0__fwd (b : Vec32) (len cap : Nat) (p : BitVec 64) (x : BitVec 32) : Result (Vec32 × Nat × Nat) :=
  match vecSet b p.toNat x with
  | .error e => .error e
  | .ok b' => .ok (b', len, cap)
