-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZN9__gnu_cxx13new_allocatorIiEC2Ev` (empty effect: void as `i32 0`). -/
def _ZN9__gnu_cxx13new_allocatorIiEC2Ev_fwd : BitVec 32 :=
  BitVec.ofNat 32 0
