-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNSt6vectorIiSaIiEE4backEv` (the `end` / `miEl` / `deref` chain fuses to `len - 1`). -/
def _ZNSt6vectorIiSaIiEE4backEv_fwd (len : Nat) : BitVec 64 :=
  BitVec.ofNat 64 len - 1
