-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNKSt6vectorIiSaIiEE12_M_check_lenEmPKc` (checked length with `maxDiff` clamp; the throw fuses to `fail`). -/
def _ZNKSt6vectorIiSaIiEE12_M_check_lenEmPKc_fwd (len : Nat) (n : BitVec 64) : Result (BitVec 64) :=
  if (BitVec.ofNat 64 2305843009213693951 - BitVec.ofNat 64 len).ult n then
    .error .AssertFail
  else if (BitVec.ofNat 64 len +
      (if (BitVec.ofNat 64 len).ult n then n
        else BitVec.ofNat 64 len)).ult (BitVec.ofNat 64 len) then
    .ok (BitVec.ofNat 64 2305843009213693951)
  else if (BitVec.ofNat 64 2305843009213693951).ult (BitVec.ofNat 64 len +
      (if (BitVec.ofNat 64 len).ult n then n
        else BitVec.ofNat 64 len)) then
    .ok (BitVec.ofNat 64 2305843009213693951)
  else
    .ok (BitVec.ofNat 64 len +
      (if (BitVec.ofNat 64 len).ult n then n
        else BitVec.ofNat 64 len))
