-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNKSt6vectorIiSaIiEE8capacityEv` (the `_M_end_of_storage` load fuses to the `cap` offset). -/
def _ZNKSt6vectorIiSaIiEE8capacityEv_fwd (cap : Nat) : BitVec 64 :=
  BitVec.ofNat 64 cap
