-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_ZNSt6vectorIiSaIiEEC2Ev` (the default-ctor chain fuses to the empty triple). -/
def _ZNSt6vectorIiSaIiEEC2Ev_fwd : Vec32 × Nat × Nat :=
  (⟨[], false⟩, 0, 0)
