-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base
import Circe.Emit.VecGrow
import Circe.Emit.VecCompose

/-- Pure translation of `_ZNSt6vectorIiSaIiEE17_M_realloc_insertIJiEEEvN9__gnu_cxx17__normal_iteratorIPiS1_EEDpOT_` (the growth composition over the frozen leaf forwards). -/
def _ZNSt6vectorIiSaIiEE17_M_realloc_insertIJiEEEvN9__gnu_cxx17__normal_iteratorIPiS1_EEDpOT__fwd (b : Vec32) (len cap : Nat) (pos : BitVec 64) (x : BitVec 32) : Result Value :=
  (stdVecCheckLenFwd len (BitVec.ofNat 64 1)).bind fun ckv =>
  (vecGrowU64 ckv).bind fun newlen =>
  (stdVecBeginFwd).bind fun bgv =>
  (vecGrowU64 bgv).bind fun bpos =>
  (stdVecMinusFwd pos bpos).bind fun miv =>
  (vecGrowI64 miv).bind fun kd =>
  (stdVecAllocFwd newlen).bind fun alv =>
  (vecGrowOwned alv).bind fun (bNew, lenA, capA) =>
  (stdVecConstructFwd bNew lenA capA kd x).bind fun conv =>
  (vecGrowOwned conv).bind fun (bC, lenC, capC) =>
  (stdVecRelocFwd b len cap bC lenC capC (BitVec.ofNat 64 0) kd
    (BitVec.ofNat 64 0)).bind fun r1v =>
  (vecGrowOwned r1v).bind fun (bR1, lenR1, capR1) =>
  (stdVecRelocFwd b len cap bR1 lenR1 capR1 kd (BitVec.ofNat 64 len)
    (kd + BitVec.ofNat 64 1)).bind fun r2v =>
  (vecGrowOwned r2v).bind fun (bR2, _, capR2) =>
  (stdVecDeallocGuardFwd b len cap (BitVec.ofNat 64 cap)).bind fun _ =>
  .ok (.stdVecOwned bR2
    ((BitVec.ofNat 64 len + BitVec.ofNat 64 1).toNat) capR2)
