-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base

/-- Pure translation of `_Z8view_sumSt17basic_string_viewIcSt11char_traitsIcEE` (range-sum over the reified bytes; `nsw` overflow is loud). -/
def _Z8view_sumSt17basic_string_viewIcSt11char_traitsIcEE_fwd (l : List (BitVec 8)) : Result (BitVec 32) :=
  go l 0
where go : List (BitVec 8) → BitVec 32 → Result (BitVec 32)
  | [], acc => .ok acc
  | x :: xs, acc => do
      let a ← checkedAddI32 acc (x.signExtend 32)
      go xs a
