-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.
-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):
-- this file is the tag-erased rendering of the verified forward function
-- (value tags dropped; pretty-printing is trusted, semantics verified).
-- Checked by `lake env lean`; see `tools/check-phase4.sh`.

import Circe.Base
import Circe.Emit.XorBuf

/-- Pure translation of `xor_n`: buffers in, xored buffer out. -/
def xor_n_fwd (o a b : List (BitVec 32)) (n : BitVec 64) : Result (List (BitVec 32)) :=
  if n.toNat ≤ o.length ∧ n.toNat ≤ a.length ∧ n.toNat ≤ b.length then
    .ok (xorNList o a b n.toNat)
  else .error .OOB
