/-
Circe.Emit.Render — rendering of accepted fragments to Lean file text.

Pure string functions only (no CoreIR/Eval dependency): one `emit*Text`
per shape plus the `emitForwardText`/`emitFileText` projections used by the
golden linkage in `Circe.Emit`. Trusted pretty-printing; the semantics are
pinned by the `emit_correct` proofs in the fragment modules.
-/

/-! ## Rendering to Lean file text -/

/-- Emission failures: only "not in the admitted fragment" exists
    (oracle/aliasing rejections live in `validate`). -/
inductive EmitError : Type
  | notFragment : String → EmitError
  deriving DecidableEq, Repr

/-- Emitted Lean code for one function: forward definition file text, plus
    an optional backward definition for borrow-returns (`choose`-shape,
    Phase 4). -/
structure EmittedFunc : Type where
  forward : String
  backward : Option String
  deriving DecidableEq, Repr

/-- File header shared by all rendered outputs. -/
def emitHeader : String :=
  "-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.\n"
  ++ "-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):\n"
  ++ "-- this file is the tag-erased rendering of the verified forward function\n"
  ++ "-- (value tags dropped; pretty-printing is trusted, semantics verified).\n"
  ++ "-- Checked by `lake env lean`; see `tools/check-phase4.sh`.\n"

/-- Render the `add` forward definition (`add_fwd`). -/
def emitAddText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}`: values in, value out (no memory). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  checkedAddI32 a b\n"

/-- Render the `incr` forward definition (`incr_fwd`), with the
    caller-side rewrite in the doc comment. -/
def emitIncrText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (`*p = *p + 1`, functionalized).\n"
  ++ s!"    Caller rewrite: `incr(&y)` becomes `y ← {name}_fwd y`. -/\n"
  ++ s!"def {name}_fwd (p : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  checkedIncrI32 p\n"

/-- Render the `add64` forward definition (`add64_fwd`, S3b). -/
def emitAdd64Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}`: values in, value out (no memory). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 64) : Result (BitVec 64) :=\n"
  ++ "  checkedAddI64 a b\n"

/-- Render the `addu64` forward definition (`addu64_fwd`, S3b:
    wrapping unsigned addition, never fails). -/
def emitAddu64Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (wrapping `u64` addition). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 64) : Result (BitVec 64) :=\n"
  ++ "  .ok (a + b)\n"

/-- Render the `choose` forward definition (`choose_fwd`). -/
def emitChooseFwdText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (borrow-return): forward selection. -/\n"
  ++ s!"def {name}_fwd (b : Bool) (x y : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  .ok (if b then x else y)\n"

/-- Render the `choose` backward definition (`choose_back`): file-local,
    concatenated after the forward text (no import of its own). -/
def emitChooseBackText (name : String) : String :=
  s!"/-- Backward propagation for `{name}`: the updated return value flows back to the selected input; the other input is unchanged. -/\n"
  ++ s!"def {name}_back (b : Bool) (x y ret : BitVec 32) : Result (BitVec 32 × BitVec 32) :=\n"
  ++ "  .ok (if b then (ret, y) else (x, ret))\n"

/-- Render the `sum_array` forward definition (`sum_fwd`): the length
    hypothesis travels in the type (`BoundedList`), so the loop bound is
    structural and the body is the verified `prefixSumU32` fold. -/
def emitSumText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (bounded `u32` accumulation, wrapping). -/\n"
  ++ "def " ++ name ++ "_fwd {n : Nat} (a : BoundedList (BitVec 32) n) : Result (BitVec 32) :=\n"
  ++ "  .ok (prefixSumU32 a.val a.val.length)\n"

/-- Render the `vec_alloc` forward definition (`vec_alloc_fwd`): the
    length comes in as a word, so the body is the verified
    `vecFillSumU32` fold over `n.toNat`. -/
def emitVecText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (uniquely-owned `u32` heap block: allocate, fill with indices, sum, free). -/\n"
  ++ "def " ++ name ++ "_fwd (n : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  vecFillSumU32 n.toNat\n"

/-- Render the `vec_copy_sum` forward definition (M1a): two live `u32`
    blocks, but the copy is value-invisible, so the body is the same
    verified `vecFillSumU32` fold over `n.toNat`. -/
def emitVec2Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (two live `u32` heap blocks: allocate two, fill `a` with indices, copy `a` into `b`, sum `b`, free both). -/\n"
  ++ "def " ++ name ++ "_fwd (n : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  vecFillSumU32 n.toNat\n"

/-- Render the `vec_alloc_u64` forward definition (M1b): the
    monomorphized `u64` mirror of `vec_alloc` — the verified
    `vecFillSumU64` fold over `n.toNat`. -/
def emitVec64Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (uniquely-owned `u64` heap block: allocate, fill with indices, sum, free). -/\n"
  ++ "def " ++ name ++ "_fwd (n : BitVec 64) : Result (BitVec 64) :=\n"
  ++ "  vecFillSumU64 n.toNat\n"

/-- Render the `vec_realloc` forward definition (M1c): a uniquely-owned
    `u32` heap block grown by `realloc` — the verified
    `vecReallocFillSumU32` fold over `n.toNat` (fill `[0,n)`, resize to
    `2*n` preserving the prefix, fill `[n,2*n)`, sum, free). -/
def emitVecReallocText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (uniquely-owned `u32` heap block grown by `realloc`: allocate, fill with indices, resize to `2*n`, fill the extension, sum, free). -/\n"
  ++ "def " ++ name ++ "_fwd (n : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  vecReallocFillSumU32 n.toNat\n"

/-- Render the `add_caller` forward definition: two sequential DAG calls
    into `add_fwd`. The file stays self-contained (only `Circe.Base` is
    imported — cross-file imports need oleans, which plain `out/` sources
    lack): the leaf body `checkedAddI32` is inlined, and
    `addCallerFwd_as_calls` certifies this is literally two `add_fwd`
    calls sequenced. -/
def emitAddCallerText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (DAG calls into `add_fwd`, twice;\n"
  ++ "    leaf body `checkedAddI32` inlined, see `addCallerFwd_as_calls`). -/\n"
  ++ s!"def {name}_fwd (x y z : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  do let t ← checkedAddI32 x y\n"
  ++ "     checkedAddI32 t z\n"

/-- Render the `sum_caller` forward definition: direct delegation to the
    `sum_array` body (same `Base` op, see `sumCallerFwd_is_call`). -/
def emitSumCallerText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to `sum_array_fwd`). -/\n"
  ++ "def " ++ name ++ "_fwd {n : Nat} (a : BoundedList (BitVec 32) n) : Result (BitVec 32) :=\n"
  ++ "  .ok (prefixSumU32 a.val a.val.length)\n"

/-- Render the `translate` forward definition: direct delegation to the
    verified `Base` op `pointTranslate` (field-wise checked addition;
    `translateFwd_*` bridge lemmas certify the delegation). -/
def emitTranslateText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (field-wise `Point` translation). -/\n"
  ++ s!"def {name}_fwd (p : Point) (dx dy : BitVec 32) : Result Point :=\n"
  ++ "  pointTranslate p dx dy\n"

/-- Render the `_ZNK5Point3sumEv` method-leaf forward definition:
    direct delegation to the verified `Base` op `pointSum`
    (`methodSumFwd_*` bridges certify the delegation). -/
def emitMethodSumText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (POD const-method `sum`: checked field addition). -/\n"
  ++ s!"def {name}_fwd (p : Point) : Result (BitVec 32) :=\n"
  ++ "  pointSum p\n"

/-- Render the `_Z13point_sum_refRK5Point` entry forward definition:
    direct delegation to `pointSum` (same `Base` op as the leaf, see
    `pointSumRefFwd_is_call`). -/
def emitPointSumRefText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `sum` method body). -/\n"
  ++ s!"def {name}_fwd (p : Point) : Result (BitVec 32) :=\n"
  ++ "  pointSum p\n"

/-- Render the `_ZN3AccC2Ev` ctor-leaf forward definition: the
    field-init (`accCtor` = `0`; `evalFuncFuel_accCtor` certifies it). -/
def emitAccCtorText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (value ctor: field-init `s = 0`). -/\n"
  ++ s!"def {name}_fwd : Result (BitVec 32) :=\n"
  ++ "  .ok accCtor\n"

/-- Render the `_ZN3Acc3addEi` method-leaf forward definition: checked
    `s += v` (`accAddFwd_ok/err` bridges certify the delegation). -/
def emitAccAddText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (mutating `add`: checked field addition). -/\n"
  ++ s!"def {name}_fwd (s v : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accAdd s v\n"

/-- Render the `_ZNK3Acc3getEv` getter-leaf forward definition
    (identity; `evalFuncFuel_accGet` certifies it). -/
def emitAccGetText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (const getter: identity). -/\n"
  ++ s!"def {name}_fwd (s : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accGet s\n"

/-- Render the `_ZN3AccD2Ev` trivial-dtor-leaf forward definition
    (no-op identity; `evalFuncFuel_accDtor` certifies it). -/
def emitAccDtorText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (trivial dtor: no-op identity). -/\n"
  ++ s!"def {name}_fwd (t : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accDtor t\n"

/-- Render the `_Z7acc_twoii` entry forward definition: direct
    delegation to `accTwo` (ctor-init + two checked adds; see
    `evalProgFunc_accTwo`). -/
def emitAccTwoText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (ctor + two `add` + `get`, dtor no-op). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accTwo a b\n"

/-- Render the `_Z11box_throughi` entry forward definition: direct
    delegation to `boxThrough` (`new` → read → `delete` passthrough;
    see `evalFuncFuel_boxThrough`). -/
def emitBoxThroughText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (`new` → read → `delete` passthrough). -/\n"
  ++ s!"def {name}_fwd (x : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  boxThrough x\n"

/-- Render the `nested_sum` forward definition: the double fold over
    `Base.nestedSumU32` (both bounds travel as words; fuel sufficiency
    is the `emit_correct_nested` side condition). -/
def emitNestedText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (nested bounded `u32` loops, wrapping). -/\n"
  ++ s!"def {name}_fwd (n m : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  .ok (nestedSumU32 n.toNat m.toNat)\n"

/-- Render the `skip_sum` forward definition (`break` caps iterations
    at 9, so no fuel hypothesis is needed downstream). -/
def emitSkipText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (bounded loop with `break`/`continue`, wrapping). -/\n"
  ++ s!"def {name}_fwd (n : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  .ok (skipSumU32 n.toNat)\n"

/-- Render the `find_eq` forward definition (early return lowered to
    `Base.findEqOut`: first match, else length, else `OOB`). Stated
    over `BitVec` (not `Value`): rendered files import only
    `Circe.Base`, and tag erasure is trusted rendering anyway. -/
def emitFindEqText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (bounded search with early return). -/\n"
  ++ s!"def {name}_fwd (a : List (BitVec 32)) (n k : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  findEqOut a n.toNat k\n"

/-- Render the `cls` forward definition (switch lowered to an
    if-chain on `ueq`). -/
def emitClsText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (`switch` lowered to an if-chain). -/\n"
  ++ s!"def {name}_fwd (x : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  if x == 0 then .ok 10\n"
  ++ "  else if x == 1 then .ok 20\n"
  ++ "  else .ok 30\n"

/-- Project an emission to its forward text (`""` on rejection, so a
    rejection also fails the golden examples below). Top-level def so
    `native_decide` can compile it. -/
def emitForwardText : Except EmitError EmittedFunc → String
  | .ok e => e.forward
  | .error _ => ""

/-- File bytes for one emission: forward text plus the backward definition
    (if any). Top-level def so `native_decide` can compile it. -/
def emitFileText : Except EmitError EmittedFunc → String
  | .ok e =>
    match e.backward with
    | none => e.forward
    | some b => e.forward ++ "\n" ++ b
  | .error _ => ""
