/-
Circe.Emit.Render — rendering of accepted fragments to Lean file text.

Pure string functions only (no CoreIR/Eval dependency): one `emit*Text`
per shape plus the `emitForwardText`/`emitFileText` projections used by the
golden linkage in `Circe.Emit`. Trusted pretty-printing; the semantics are
pinned by the `emit_correct` proofs in the fragment modules.
-/

/-! ## Rendering to Lean file text -/

/-- Emission failures: only "not in the admitted fragment" exists
    (oracle/aliasing rejections live in `validate`). -/
inductive EmitError : Type
  | notFragment : String → EmitError
  deriving DecidableEq, Repr

/-- Emitted Lean code for one function: forward definition file text, plus
    an optional backward definition for borrow-returns (`choose`-shape,
    Phase 4). -/
structure EmittedFunc : Type where
  forward : String
  backward : Option String
  deriving DecidableEq, Repr

/-- File header shared by all rendered outputs. -/
def emitHeader : String :=
  "-- Generated by the Circe emitter (Phase 4) from validated CoreIR. Do not edit.\n"
  ++ "-- Emitter correctness (`Circe.Emit.emit_correct_add/incr/choose/sum`):\n"
  ++ "-- this file is the tag-erased rendering of the verified forward function\n"
  ++ "-- (value tags dropped; pretty-printing is trusted, semantics verified).\n"
  ++ "-- Checked by `lake env lean`; see `tools/check-phase4.sh`.\n"

/-- Render the `add` forward definition (`add_fwd`). -/
def emitAddText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}`: values in, value out (no memory). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  checkedAddI32 a b\n"

/-- Render the `incr` forward definition (`incr_fwd`), with the
    caller-side rewrite in the doc comment. -/
def emitIncrText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (`*p = *p + 1`, functionalized).\n"
  ++ s!"    Caller rewrite: `incr(&y)` becomes `y ← {name}_fwd y`. -/\n"
  ++ s!"def {name}_fwd (p : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  checkedIncrI32 p\n"

/-- Render the `add64` forward definition (`add64_fwd`, S3b). -/
def emitAdd64Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}`: values in, value out (no memory). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 64) : Result (BitVec 64) :=\n"
  ++ "  checkedAddI64 a b\n"

/-- Render the `addu64` forward definition (`addu64_fwd`, S3b:
    wrapping unsigned addition, never fails). -/
def emitAddu64Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (wrapping `u64` addition). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 64) : Result (BitVec 64) :=\n"
  ++ "  .ok (a + b)\n"

/-- Render the `choose` forward definition (`choose_fwd`). -/
def emitChooseFwdText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (borrow-return): forward selection. -/\n"
  ++ s!"def {name}_fwd (b : Bool) (x y : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  .ok (if b then x else y)\n"

/-- Render the `choose` backward definition (`choose_back`): file-local,
    concatenated after the forward text (no import of its own). -/
def emitChooseBackText (name : String) : String :=
  s!"/-- Backward propagation for `{name}`: the updated return value flows back to the selected input; the other input is unchanged. -/\n"
  ++ s!"def {name}_back (b : Bool) (x y ret : BitVec 32) : Result (BitVec 32 × BitVec 32) :=\n"
  ++ "  .ok (if b then (ret, y) else (x, ret))\n"

/-- Render the `sum_array` forward definition (`sum_fwd`): the length
    hypothesis travels in the type (`BoundedList`), so the loop bound is
    structural and the body is the verified `prefixSumU32` fold. -/
def emitSumText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (bounded `u32` accumulation, wrapping). -/\n"
  ++ "def " ++ name ++ "_fwd {n : Nat} (a : BoundedList (BitVec 32) n) : Result (BitVec 32) :=\n"
  ++ "  .ok (prefixSumU32 a.val a.val.length)\n"

/-- Render the `vec_alloc` forward definition (`vec_alloc_fwd`): the
    length comes in as a word, so the body is the verified
    `vecFillSumU32` fold over `n.toNat`. -/
def emitVecText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (uniquely-owned `u32` heap block: allocate, fill with indices, sum, free). -/\n"
  ++ "def " ++ name ++ "_fwd (n : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  vecFillSumU32 n.toNat\n"

/-- Render the `vec_copy_sum` forward definition (M1a): two live `u32`
    blocks, but the copy is value-invisible, so the body is the same
    verified `vecFillSumU32` fold over `n.toNat`. -/
def emitVec2Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (two live `u32` heap blocks: allocate two, fill `a` with indices, copy `a` into `b`, sum `b`, free both). -/\n"
  ++ "def " ++ name ++ "_fwd (n : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  vecFillSumU32 n.toNat\n"

/-- Render the `vec_alloc_u64` forward definition (M1b): the
    monomorphized `u64` mirror of `vec_alloc` — the verified
    `vecFillSumU64` fold over `n.toNat`. -/
def emitVec64Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (uniquely-owned `u64` heap block: allocate, fill with indices, sum, free). -/\n"
  ++ "def " ++ name ++ "_fwd (n : BitVec 64) : Result (BitVec 64) :=\n"
  ++ "  vecFillSumU64 n.toNat\n"

/-- Render the `vec_realloc` forward definition (M1c): a uniquely-owned
    `u32` heap block grown by `realloc` — the verified
    `vecReallocFillSumU32` fold over `n.toNat` (fill `[0,n)`, resize to
    `2*n` preserving the prefix, fill `[n,2*n)`, sum, free). -/
def emitVecReallocText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ "/-- Pure translation of `" ++ name ++ "` (uniquely-owned `u32` heap block grown by `realloc`: allocate, fill with indices, resize to `2*n`, fill the extension, sum, free). -/\n"
  ++ "def " ++ name ++ "_fwd (n : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  vecReallocFillSumU32 n.toNat\n"

/-- Render the `add_caller` forward definition: two sequential DAG calls
    into `add_fwd`. The file stays self-contained (only `Circe.Base` is
    imported — cross-file imports need oleans, which plain `out/` sources
    lack): the leaf body `checkedAddI32` is inlined, and
    `addCallerFwd_as_calls` certifies this is literally two `add_fwd`
    calls sequenced. -/
def emitAddCallerText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (DAG calls into `add_fwd`, twice;\n"
  ++ "    leaf body `checkedAddI32` inlined, see `addCallerFwd_as_calls`). -/\n"
  ++ s!"def {name}_fwd (x y z : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  do let t ← checkedAddI32 x y\n"
  ++ "     checkedAddI32 t z\n"

/-- Render the `sum_caller` forward definition: direct delegation to the
    `sum_array` body (same `Base` op, see `sumCallerFwd_is_call`). -/
def emitSumCallerText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to `sum_array_fwd`). -/\n"
  ++ "def " ++ name ++ "_fwd {n : Nat} (a : BoundedList (BitVec 32) n) : Result (BitVec 32) :=\n"
  ++ "  .ok (prefixSumU32 a.val a.val.length)\n"

/-- Render the `add3` overload-leaf forward definition: two sequential
    checked adds (leaf body `checkedAddI32` inlined twice, see
    `add3Fwd_ok/err`). -/
def emitAdd3Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (3-`i32` overload leaf: two threaded `nsw` adds). -/\n"
  ++ s!"def {name}_fwd (x y z : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  do let t ← checkedAddI32 x y\n"
  ++ "     checkedAddI32 t z\n"

/-- Render the `use_add` entry forward definition: direct delegation to
    the resolved overload leaf body (`checkedAddI32`, see
    `useAddFwd_is_call`). -/
def emitUseAddText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `_Z3addii` overload body). -/\n"
  ++ s!"def {name}_fwd (x y : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  checkedAddI32 x y\n"

/-- Render the `use_ns_add` entry forward definition: direct delegation
    to the namespaced leaf body (see `useNsAddFwd_is_call`). -/
def emitUseNsAddText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `_ZN2ns3addEii` namespaced body). -/\n"
  ++ s!"def {name}_fwd (x y : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  checkedAddI32 x y\n"

/-- Render the `use_tadd32` entry forward definition: direct delegation
    to the 32-bit instantiation body (see `useTadd32Fwd_is_call`). -/
def emitUseTadd32Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `_Z4taddIiET_S0_S0_` instantiation body). -/\n"
  ++ s!"def {name}_fwd (x y : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  checkedAddI32 x y\n"

/-- Render the `use_tadd64` entry forward definition: direct delegation
    to the 64-bit instantiation body (see `useTadd64Fwd_is_call`). -/
def emitUseTadd64Text (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `_Z4taddIlET_S0_S0_` instantiation body). -/\n"
  ++ s!"def {name}_fwd (x y : BitVec 64) : Result (BitVec 64) :=\n"
  ++ "  checkedAddI64 x y\n"

/-- Render the `_S_ref` leaf forward definition: the word at `u64`
    index `n` of the word list, `OOB` off the end (the tag-erased
    `arrayRefFwd`). -/
def emitArrayRefText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (unchecked `u64` index into the 4-word `i32` array). -/\n"
  ++ s!"def {name}_fwd (t : List (BitVec 32)) (n : BitVec 64) : Result (BitVec 32) :=\n"
  ++ "  match t[n.toNat]? with\n"
  ++ "  | some x => .ok x\n"
  ++ "  | none => .error .OOB\n"

/-- Render the `operator[]` entry forward definition: the same read
    (the call edge is fused, so the rendering is the leaf rendering
    by definition, cf. `arrayAtFwd_is_call`). -/
def emitArrayAtText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `_S_ref` unchecked-index body). -/\n"
  ++ s!"def {name}_fwd (a : List (BitVec 32)) (n : BitVec 64) : Result (BitVec 32) :=\n"
  ++ "  match a[n.toNat]? with\n"
  ++ "  | some x => .ok x\n"
  ++ "  | none => .error .OOB\n"

/-- Render the `array_sum` entry forward definition: three threaded
    `nsw` adds over the four words (the tag-erased `arraySumFwd`). -/
def emitArraySumText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (4 reads through `operator[]`, three threaded `nsw` adds). -/\n"
  ++ s!"def {name}_fwd (a b c d : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  do let t ← checkedAddI32 a b\n"
  ++ "     let u ← checkedAddI32 t c\n"
  ++ "     checkedAddI32 u d\n"

/-- Render the `_M_is_engaged` leaf forward definition: the engaged
    bit of the optional (the tag-erased `optHasFwd`, value tags
    dropped). -/
def emitOptHasText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `_M_engaged` bit load). -/\n"
  ++ s!"def {name}_fwd (o : Option (BitVec 32)) : Bool :=\n"
  ++ "  o.isSome\n"

/-- Render the `has_value` entry forward definition: the same bit
    (the call edge is fused, cf. `optHasValueFwd_is_call`). -/
def emitOptHasValueText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `_M_is_engaged` bit body). -/\n"
  ++ s!"def {name}_fwd (o : Option (BitVec 32)) : Bool :=\n"
  ++ "  o.isSome\n"

/-- Render the payload `_M_get` leaf forward definition: the payload
    word, `AssertFail` when disengaged (the tag-erased `optGetFwd`). -/
def emitOptGetText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `_M_value` word load; disengaged is `AssertFail`). -/\n"
  ++ s!"def {name}_fwd (o : Option (BitVec 32)) : Result (BitVec 32) :=\n"
  ++ "  match o with\n"
  ++ "  | some x => .ok x\n"
  ++ "  | none => .error .AssertFail\n"

/-- Render the impl `_M_get` entry forward definition: pure
    delegation to the payload body (the dead assert scope is
    dropped). -/
def emitOptImplGetText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the payload `_M_get` word body). -/\n"
  ++ s!"def {name}_fwd (o : Option (BitVec 32)) : Result (BitVec 32) :=\n"
  ++ "  match o with\n"
  ++ "  | some x => .ok x\n"
  ++ "  | none => .error .AssertFail\n"

/-- Render the `operator*` entry forward definition: the same word
    (two call edges fused, cf. `optDerefOpFwd_is_call`). -/
def emitOptDerefOpText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the fused `operator*` → impl → payload word read). -/\n"
  ++ s!"def {name}_fwd (o : Option (BitVec 32)) : Result (BitVec 32) :=\n"
  ++ "  match o with\n"
  ++ "  | some x => .ok x\n"
  ++ "  | none => .error .AssertFail\n"

/-- Render the `opt_deref` entry forward definition: the payload word
    on engaged, the `-1` sentinel on disengaged (the tag-erased
    `optDerefFwd`). -/
def emitOptDerefText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (guarded deref: word on engaged, `-1` sentinel otherwise). -/\n"
  ++ s!"def {name}_fwd (o : Option (BitVec 32)) : Result (BitVec 32) :=\n"
  ++ "  match o with\n"
  ++ "  | some x => .ok x\n"
  ++ "  | none => .ok (-1)\n"

/-- Render the `_M_extent` leaf forward definition: the reified
    length as a `u64` word (the tag-erased `spanExtentFwd`). -/
def emitSpanExtentText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `_M_extent_value` word load). -/\n"
  ++ s!"def {name}_fwd (l : List (BitVec 32)) : BitVec 64 :=\n"
  ++ "  BitVec.ofNat 64 l.length\n"

/-- Render the `size` entry forward definition: the same read (the
    call edge is fused, cf. `spanSizeFwd_is_call`). -/
def emitSpanSizeText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `_M_extent` length body). -/\n"
  ++ s!"def {name}_fwd (l : List (BitVec 32)) : BitVec 64 :=\n"
  ++ "  BitVec.ofNat 64 l.length\n"

/-- Render the `operator[]` leaf forward definition: the word at
    the `u64` index, `OOB` off the end (the tag-erased
    `spanIndexFwd`). -/
def emitSpanIndexText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the fused `operator[]` word read; `OOB` off the end). -/\n"
  ++ s!"def {name}_fwd (l : List (BitVec 32)) (n : BitVec 64) : Result (BitVec 32) :=\n"
  ++ "  match l[n.toNat]? with\n"
  ++ "  | some x => .ok x\n"
  ++ "  | none => .error .OOB\n"

/-- Render the `span_sum` entry forward definition: the
    checked-add fold over the reified words (the tag-erased
    `spanSumFwd`; the local `go` mirrors `spanFold` arm for arm,
    `nsw` errors short-circuit through the `do`). -/
def emitSpanSumText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (index-sum over the reified words; `nsw` overflow is loud). -/\n"
  ++ s!"def {name}_fwd (l : List (BitVec 32)) : Result (BitVec 32) :=\n"
  ++ "  go l 0\n"
  ++ "where go : List (BitVec 32) → BitVec 32 → Result (BitVec 32)\n"
  ++ "  | [], acc => .ok acc\n"
  ++ "  | x :: xs, acc => do\n"
  ++ "      let a ← checkedAddI32 acc x\n"
  ++ "      go xs a\n"

/-- Render the vector `size` leaf forward definition: the reified
    length as a `u64` word (the tag-erased `stdVecSizeFwd`). -/
def emitStdVecSizeText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `_M_finish` / `_M_start` `ptr_diff` + `cast`). -/\n"
  ++ s!"def {name}_fwd (l : List (BitVec 32)) : BitVec 64 :=\n"
  ++ "  BitVec.ofNat 64 l.length\n"

/-- Render the vector `operator[]` leaf forward definition: the
    word at the `u64` index, `OOB` off the end (the tag-erased
    `stdVecIndexFwd`). -/
def emitStdVecIndexText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the fused `operator[]` word read; `OOB` off the end). -/\n"
  ++ s!"def {name}_fwd (l : List (BitVec 32)) (n : BitVec 64) : Result (BitVec 32) :=\n"
  ++ "  match l[n.toNat]? with\n"
  ++ "  | some x => .ok x\n"
  ++ "  | none => .error .OOB\n"

/-- Render the `vec_read_sum` entry forward definition: the
    checked-add fold over the reified words (the tag-erased
    `stdVecReadSumFwd`; the local `go` mirrors `stdVecFold` arm for
    arm, `nsw` errors short-circuit through the `do`). -/
def emitStdVecReadSumText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (index-sum over the reified words; `nsw` overflow is loud). -/\n"
  ++ s!"def {name}_fwd (l : List (BitVec 32)) : Result (BitVec 32) :=\n"
  ++ "  go l 0\n"
  ++ "where go : List (BitVec 32) → BitVec 32 → Result (BitVec 32)\n"
  ++ "  | [], acc => .ok acc\n"
  ++ "  | x :: xs, acc => do\n"
  ++ "      let a ← checkedAddI32 acc x\n"
  ++ "      go xs a\n"

/-- Render the default-ctor forward definition: the empty triple
    (the tag-erased `stdVecEmptyCtorFwd`). -/
def emitStdVecEmptyCtorText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the default-ctor chain fuses to the empty triple). -/\n"
  ++ s!"def {name}_fwd : Vec32 × Nat × Nat :=\n"
  ++ "  (⟨[], false⟩, 0, 0)\n"

/-- Render the empty-effect forward definition: void as `i32 0`
    (the tag-erased `stdVecUnitFwd`). -/
def emitStdVecUnitText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (empty effect: void as `i32 0`). -/\n"
  ++ s!"def {name}_fwd : BitVec 32 :=\n"
  ++ "  BitVec.ofNat 32 0\n"

/-- Render the destructor forward definition: the `0 < cap`-guarded
    consume (the tag-erased `stdVecDtorFwd`, triple threading). -/
def emitStdVecDtorText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `0 < cap`-guarded consume; the destroy range is a no-op for `int`). -/\n"
  ++ s!"def {name}_fwd (b : Vec32) (len cap : Nat) : Result (Vec32 × Nat × Nat) :=\n"
  ++ "  if 0 < cap then\n"
  ++ "    match vecFree b with\n"
  ++ "    | .error e => .error e\n"
  ++ "    | .ok b' => .ok (b', len, cap)\n"
  ++ "  else .ok (b, len, cap)\n"

/-- Render the destroy-range forward definition (the tag-erased
    `stdVecDestroyNoopFwd`). -/
def emitStdVecDestroyNoopText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the trivial-`int` destroy range: nothing destroyed). -/\n"
  ++ s!"def {name}_fwd (_a _b : BitVec 64) : BitVec 32 :=\n"
  ++ "  BitVec.ofNat 32 0\n"

/-- Render the element-destroy forward definition (the tag-erased
    `stdVecDestroyPtrFwd`). -/
def emitStdVecDestroyPtrText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (element destroy: no-op for `int`). -/\n"
  ++ s!"def {name}_fwd (_p : BitVec 64) : BitVec 32 :=\n"
  ++ "  BitVec.ofNat 32 0\n"

/-- Render the allocator-projection forward definition (the
    tag-erased `stdVecGetTpFwd`). -/
def emitStdVecGetTpText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `_M_impl` access fuses to the erased allocator). -/\n"
  ++ s!"def {name}_fwd : BitVec 32 :=\n"
  ++ "  BitVec.ofNat 32 0\n"

/-- Render the max-size forward definition: the `diffmax` const
    (the tag-erased `stdVecDiffMaxFwd`). -/
def emitStdVecDiffMaxText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the max-size chain folds to `diffmax`). -/\n"
  ++ s!"def {name}_fwd : BitVec 64 :=\n"
  ++ "  BitVec.ofNat 64 2305843009213693951\n"

/-- Render the `std::max` forward definition (the tag-erased
    `stdVecMaxFwd`). -/
def emitStdVecMaxText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the early-return-`if` max over `u64`). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 64) : BitVec 64 :=\n"
  ++ "  if a.ult b then b else a\n"

/-- Render the `std::min` forward definition (the tag-erased
    `stdVecMinFwd`). -/
def emitStdVecMinText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the early-return-`if` min over `u64`). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 64) : BitVec 64 :=\n"
  ++ "  if b.ult a then b else a\n"

/-- Render the `_M_check_len` forward definition (the tag-erased
    `stdVecCheckLenFwd`: `length_error` is loud, over-`maxDiff`
    clamps to `maxDiff`). -/
def emitStdVecCheckLenText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (checked length with `maxDiff` clamp; the throw fuses to `fail`). -/\n"
  ++ s!"def {name}_fwd (len : Nat) (n : BitVec 64) : Result (BitVec 64) :=\n"
  ++ "  if (BitVec.ofNat 64 2305843009213693951 - BitVec.ofNat 64 len).ult n then\n"
  ++ "    .error .AssertFail\n"
  ++ "  else if (BitVec.ofNat 64 len +\n"
  ++ "      (if (BitVec.ofNat 64 len).ult n then n\n"
  ++ "        else BitVec.ofNat 64 len)).ult (BitVec.ofNat 64 len) then\n"
  ++ "    .ok (BitVec.ofNat 64 2305843009213693951)\n"
  ++ "  else if (BitVec.ofNat 64 2305843009213693951).ult (BitVec.ofNat 64 len +\n"
  ++ "      (if (BitVec.ofNat 64 len).ult n then n\n"
  ++ "        else BitVec.ofNat 64 len)) then\n"
  ++ "    .ok (BitVec.ofNat 64 2305843009213693951)\n"
  ++ "  else\n"
  ++ "    .ok (BitVec.ofNat 64 len +\n"
  ++ "      (if (BitVec.ofNat 64 len).ult n then n\n"
  ++ "        else BitVec.ofNat 64 len))\n"

/-- Render the `begin` forward definition (the tag-erased
    `stdVecBeginFwd`). -/
def emitStdVecBeginText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `_M_start` load fuses to the `0` offset). -/\n"
  ++ s!"def {name}_fwd : BitVec 64 :=\n"
  ++ "  BitVec.ofNat 64 0\n"

/-- Render the `end` forward definition (the tag-erased
    `stdVecEndFwd`). -/
def emitStdVecEndText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `_M_finish` load fuses to the `len` offset). -/\n"
  ++ s!"def {name}_fwd (len : Nat) : BitVec 64 :=\n"
  ++ "  BitVec.ofNat 64 len\n"

/-- Render the `back` forward definition (the tag-erased
    `stdVecBackFwd`). -/
def emitStdVecBackText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `end` / `miEl` / `deref` chain fuses to `len - 1`). -/\n"
  ++ s!"def {name}_fwd (len : Nat) : BitVec 64 :=\n"
  ++ "  BitVec.ofNat 64 len - 1\n"

/-- Render the iterator-identity forward definition (the tag-erased
    `stdVecIterIdFwd`). -/
def emitStdVecIterIdText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the stored pointer is the offset). -/\n"
  ++ s!"def {name}_fwd (x : BitVec 64) : BitVec 64 :=\n"
  ++ "  x\n"

/-- Render the `miEl` forward definition (the tag-erased
    `stdVecMinusElFwd`). -/
def emitStdVecMinusElText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (`cir.minus` + `ptr_stride` fuse to wrapping `usub`). -/\n"
  ++ s!"def {name}_fwd (it n : BitVec 64) : BitVec 64 :=\n"
  ++ "  it - n\n"

/-- Render the `mi` forward definition (the tag-erased
    `stdVecMinusFwd`; `s64` erases to the 64-bit word). -/
def emitStdVecMinusText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the double `base` + `ptr_diff` fuse to bit-exact `s64diff`). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 64) : BitVec 64 :=\n"
  ++ "  a - b\n"

/-- Render the allocate forward definition (the tag-erased
    `stdVecAllocFwd`: `n > maxDiff` is loud, `n == 0` is the empty
    triple, else fresh storage). -/
def emitStdVecAllocText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (fresh storage like `boxNew`; the over-max throw pair fuses to `fail`). -/\n"
  ++ s!"def {name}_fwd (n : BitVec 64) : Result (Vec32 × Nat × Nat) :=\n"
  ++ "  if (BitVec.ofNat 64 0).ult n then\n"
  ++ "    if (BitVec.ofNat 64 2305843009213693951).ult n then .error .AssertFail\n"
  ++ "    else .ok (⟨List.replicate n.toNat 0, false⟩, 0, n.toNat)\n"
  ++ "  else .ok (⟨[], false⟩, 0, 0)\n"

/-- Render the deallocate forward definition (the tag-erased
    `stdVecDeallocFwd`: unconditional consume). -/
def emitStdVecDeallocText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (unconditional consume; operator `delete` consumes the token). -/\n"
  ++ s!"def {name}_fwd (b : Vec32) (len cap : Nat) : Result (Vec32 × Nat × Nat) :=\n"
  ++ "  match vecFree b with\n"
  ++ "  | .error e => .error e\n"
  ++ "  | .ok b' => .ok (b', len, cap)\n"

/-- Render the `_M_deallocate` forward definition (the tag-erased
    `stdVecDeallocGuardFwd`: the `n == 0` test around the consume). -/
def emitStdVecDeallocGuardText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the `ptr_to_bool` guard as the `n == 0` test). -/\n"
  ++ s!"def {name}_fwd (b : Vec32) (len cap : Nat) (n : BitVec 64) : Result (Vec32 × Nat × Nat) :=\n"
  ++ "  if (BitVec.ofNat 64 0).ult n then\n"
  ++ "    match vecFree b with\n"
  ++ "    | .error e => .error e\n"
  ++ "    | .ok b' => .ok (b', len, cap)\n"
  ++ "  else .ok (b, len, cap)\n"

/-- Render the `construct` forward definition (the tag-erased
    `stdVecConstructFwd`: placement store, updated triple). -/
def emitStdVecConstructText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (placement store of the `i32` word at the `u64` offset). -/\n"
  ++ s!"def {name}_fwd (b : Vec32) (len cap : Nat) (p : BitVec 64) (x : BitVec 32) : Result (Vec32 × Nat × Nat) :=\n"
  ++ "  match vecSet b p.toNat x with\n"
  ++ "  | .error e => .error e\n"
  ++ "  | .ok b' => .ok (b', len, cap)\n"

/-- Render the relocate forward definition (the tag-erased
    `stdVecRelocFwd`: the `memmove`-fused bulk copy). -/
def emitStdVecRelocText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (the copy loop over the destination triple; the source triple is unchanged). -/\n"
  ++ s!"def {name}_fwd (bS : Vec32) (lenS : Nat) (_capS : Nat) (bD : Vec32) (lenD capD : Nat) (first last result : BitVec 64) : Result (Vec32 × Nat × Nat) :=\n"
  ++ "  match stdVecBlitFold bS.val lenS bS.freed bD result.toNat first.toNat (last.toNat - first.toNat) with\n"
  ++ "  | .error e => .error e\n"
  ++ "  | .ok bD' => .ok (bD', lenD, capD)\n"

/-- Render the `_M_realloc_insert` growth composition (the tag-erased
    `stdVecGrowReallocFwd`: the bind chain over the frozen b1 leaf
    forwards). -/
def emitStdVecGrowReallocText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\nimport Circe.Emit.VecGrow\nimport Circe.Emit.VecCompose\n\n"
  ++ s!"/-- Pure translation of `{name}` (the growth composition over the frozen leaf forwards). -/\n"
  ++ s!"def {name}_fwd (b : Vec32) (len cap : Nat) (pos : BitVec 64) (x : BitVec 32) : Result Value :=\n"
  ++ "  (stdVecCheckLenFwd len (BitVec.ofNat 64 1)).bind fun ckv =>\n"
  ++ "  (vecGrowU64 ckv).bind fun newlen =>\n"
  ++ "  (stdVecBeginFwd).bind fun bgv =>\n"
  ++ "  (vecGrowU64 bgv).bind fun bpos =>\n"
  ++ "  (stdVecMinusFwd pos bpos).bind fun miv =>\n"
  ++ "  (vecGrowI64 miv).bind fun kd =>\n"
  ++ "  (stdVecAllocFwd newlen).bind fun alv =>\n"
  ++ "  (vecGrowOwned alv).bind fun (bNew, lenA, capA) =>\n"
  ++ "  (stdVecConstructFwd bNew lenA capA kd x).bind fun conv =>\n"
  ++ "  (vecGrowOwned conv).bind fun (bC, lenC, capC) =>\n"
  ++ "  (stdVecRelocFwd b len cap bC lenC capC (BitVec.ofNat 64 0) kd\n"
  ++ "    (BitVec.ofNat 64 0)).bind fun r1v =>\n"
  ++ "  (vecGrowOwned r1v).bind fun (bR1, lenR1, capR1) =>\n"
  ++ "  (stdVecRelocFwd b len cap bR1 lenR1 capR1 kd (BitVec.ofNat 64 len)\n"
  ++ "    (kd + BitVec.ofNat 64 1)).bind fun r2v =>\n"
  ++ "  (vecGrowOwned r2v).bind fun (bR2, _, capR2) =>\n"
  ++ "  (stdVecDeallocGuardFwd b len cap (BitVec.ofNat 64 cap)).bind fun _ =>\n"
  ++ "  .ok (.stdVecOwned bR2\n"
  ++ "    ((BitVec.ofNat 64 len + BitVec.ofNat 64 1).toNat) capR2)\n"

/-- Render the `emplace_back` composer (the tag-erased
    `stdVecEmplaceBackFwd`: capacity dispatch — slow arm is the
    realloc bind chain at `pos = len`, fast arm is the construct
    forward at `len` with length `len + 1`). -/
def emitStdVecEmplaceBackText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\nimport Circe.Emit.VecGrow\nimport Circe.Emit.VecCompose\n\n"
  ++ s!"/-- Pure translation of `{name}` (fast construct / slow realloc composition over the frozen leaf forwards). -/\n"
  ++ s!"def {name}_fwd (b : Vec32) (len cap : Nat) (x : BitVec 32) : Result Value :=\n"
  ++ "  if len == cap then\n"
  ++ "    (stdVecCheckLenFwd len (BitVec.ofNat 64 1)).bind fun ckv =>\n"
  ++ "    (vecGrowU64 ckv).bind fun newlen =>\n"
  ++ "    (stdVecBeginFwd).bind fun bgv =>\n"
  ++ "    (vecGrowU64 bgv).bind fun bpos =>\n"
  ++ "    (stdVecMinusFwd (BitVec.ofNat 64 len) bpos).bind fun miv =>\n"
  ++ "    (vecGrowI64 miv).bind fun kd =>\n"
  ++ "    (stdVecAllocFwd newlen).bind fun alv =>\n"
  ++ "    (vecGrowOwned alv).bind fun (bNew, lenA, capA) =>\n"
  ++ "    (stdVecConstructFwd bNew lenA capA kd x).bind fun conv =>\n"
  ++ "    (vecGrowOwned conv).bind fun (bC, lenC, capC) =>\n"
  ++ "    (stdVecRelocFwd b len cap bC lenC capC (BitVec.ofNat 64 0) kd\n"
  ++ "      (BitVec.ofNat 64 0)).bind fun r1v =>\n"
  ++ "    (vecGrowOwned r1v).bind fun (bR1, lenR1, capR1) =>\n"
  ++ "    (stdVecRelocFwd b len cap bR1 lenR1 capR1 kd (BitVec.ofNat 64 len)\n"
  ++ "      (kd + BitVec.ofNat 64 1)).bind fun r2v =>\n"
  ++ "    (vecGrowOwned r2v).bind fun (bR2, _, capR2) =>\n"
  ++ "    (stdVecDeallocGuardFwd b len cap (BitVec.ofNat 64 cap)).bind fun _ =>\n"
  ++ "    .ok (.stdVecOwned bR2\n"
  ++ "      ((BitVec.ofNat 64 len + BitVec.ofNat 64 1).toNat) capR2)\n"
  ++ "  else (stdVecConstructFwd b len cap (BitVec.ofNat 64 len) x).bind fun conv =>\n"
  ++ "    (vecGrowOwned conv).bind fun (b', _, _) =>\n"
  ++ "    .ok (.stdVecOwned b' (len + 1) cap)\n"

/-- Render the `push_back` forwarder definition: direct delegation to
    the verified `stdVecPushBackFwd` (the discarded reference never
    affects the triple; cf. `emitTranslateText` delegating to the
    verified `Base` op). -/
def emitStdVecPushBackText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\nimport Circe.Emit.VecGrow\nimport Circe.Emit.VecCompose\n\n"
  ++ s!"/-- Pure translation of `{name}` (single-`callProg` forwarder into the proved `emplace_back` composer). -/\n"
  ++ s!"def {name}_fwd (b : Vec32) (len cap : Nat) (x : BitVec 32) : Result Value :=\n"
  ++ "  stdVecPushBackFwd b len cap x\n"

/-- Render the `translate` forward definition: direct delegation to the
    verified `Base` op `pointTranslate` (field-wise checked addition;
    `translateFwd_*` bridge lemmas certify the delegation). -/
def emitTranslateText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (field-wise `Point` translation). -/\n"
  ++ s!"def {name}_fwd (p : Point) (dx dy : BitVec 32) : Result Point :=\n"
  ++ "  pointTranslate p dx dy\n"

/-- Render the `_ZNK5Point3sumEv` method-leaf forward definition:
    direct delegation to the verified `Base` op `pointSum`
    (`methodSumFwd_*` bridges certify the delegation). -/
def emitMethodSumText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (POD const-method `sum`: checked field addition). -/\n"
  ++ s!"def {name}_fwd (p : Point) : Result (BitVec 32) :=\n"
  ++ "  pointSum p\n"

/-- Render the `_Z13point_sum_refRK5Point` entry forward definition:
    direct delegation to `pointSum` (same `Base` op as the leaf, see
    `pointSumRefFwd_is_call`). -/
def emitPointSumRefText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (delegates to the `sum` method body). -/\n"
  ++ s!"def {name}_fwd (p : Point) : Result (BitVec 32) :=\n"
  ++ "  pointSum p\n"

/-- Render the `_ZN3AccC2Ev` ctor-leaf forward definition: the
    field-init (`accCtor` = `0`; `evalFuncFuel_accCtor` certifies it). -/
def emitAccCtorText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (value ctor: field-init `s = 0`). -/\n"
  ++ s!"def {name}_fwd : Result (BitVec 32) :=\n"
  ++ "  .ok accCtor\n"

/-- Render the `_ZN3Acc3addEi` method-leaf forward definition: checked
    `s += v` (`accAddFwd_ok/err` bridges certify the delegation). -/
def emitAccAddText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (mutating `add`: checked field addition). -/\n"
  ++ s!"def {name}_fwd (s v : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accAdd s v\n"

/-- Render the `_ZNK3Acc3getEv` getter-leaf forward definition
    (identity; `evalFuncFuel_accGet` certifies it). -/
def emitAccGetText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (const getter: identity). -/\n"
  ++ s!"def {name}_fwd (s : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accGet s\n"

/-- Render the `_ZN3AccD2Ev` trivial-dtor-leaf forward definition
    (no-op identity; `evalFuncFuel_accDtor` certifies it). -/
def emitAccDtorText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (trivial dtor: no-op identity). -/\n"
  ++ s!"def {name}_fwd (t : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accDtor t\n"

/-- Render the `_Z7acc_twoii` entry forward definition: direct
    delegation to `accTwo` (ctor-init + two checked adds; see
    `evalProgFunc_accTwo`). -/
def emitAccTwoText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (ctor + two `add` + `get`, dtor no-op). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accTwo a b\n"

/-- Render the `_ZN3AccC2EOS_` move-ctor-leaf forward definition:
    destination takes the source word (`accMoveCtorFwd_is_ok`
    certifies it; the source-zeroing store is entry-level). -/
def emitAccMoveCtorText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (move ctor: dst takes src word). -/\n"
  ++ s!"def {name}_fwd (d s : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  accMoveCtor d s\n"

/-- Render the `_Z8move_accii` entry forward definition: direct
    delegation to `moveAcc` (ctor + `add` + move + zeroing `assign` +
    `add` + `get`, dtors no-op; see `evalProgFunc_moveAcc`). -/
def emitMoveAccText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (move + two `add` + `get`, dtors no-op). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  moveAcc a b\n"

/-- Render the `_Z11scope_earlyii` entry forward definition: direct
    delegation to `scopeEarly` (early `get` on `a == b`, else second
    `add` + `get`, dtors no-op; see `evalProgFunc_scopeEarly`). -/
def emitScopeEarlyText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (early return + `add` + `get`, dtors no-op). -/\n"
  ++ s!"def {name}_fwd (a b : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  scopeEarly a b\n"

/-- Render the `_Z11box_throughi` entry forward definition: direct
    delegation to `boxThrough` (`new` → read → `delete` passthrough;
    see `evalFuncFuel_boxThrough`). -/
def emitBoxThroughText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (`new` → read → `delete` passthrough). -/\n"
  ++ s!"def {name}_fwd (x : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  boxThrough x\n"

/-- Render the `nested_sum` forward definition: the double fold over
    `Base.nestedSumU32` (both bounds travel as words; fuel sufficiency
    is the `emit_correct_nested` side condition). -/
def emitNestedText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (nested bounded `u32` loops, wrapping). -/\n"
  ++ s!"def {name}_fwd (n m : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  .ok (nestedSumU32 n.toNat m.toNat)\n"

/-- Render the `skip_sum` forward definition (`break` caps iterations
    at 9, so no fuel hypothesis is needed downstream). -/
def emitSkipText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (bounded loop with `break`/`continue`, wrapping). -/\n"
  ++ s!"def {name}_fwd (n : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  .ok (skipSumU32 n.toNat)\n"

/-- Render the `find_eq` forward definition (early return lowered to
    `Base.findEqOut`: first match, else length, else `OOB`). Stated
    over `BitVec` (not `Value`): rendered files import only
    `Circe.Base`, and tag erasure is trusted rendering anyway. -/
def emitFindEqText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (bounded search with early return). -/\n"
  ++ s!"def {name}_fwd (a : List (BitVec 32)) (n k : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  findEqOut a n.toNat k\n"

/-- Render the `cls` forward definition (switch lowered to an
    if-chain on `ueq`). -/
def emitClsText (name : String) : String :=
  emitHeader
  ++ "\nimport Circe.Base\n\n"
  ++ s!"/-- Pure translation of `{name}` (`switch` lowered to an if-chain). -/\n"
  ++ s!"def {name}_fwd (x : BitVec 32) : Result (BitVec 32) :=\n"
  ++ "  if x == 0 then .ok 10\n"
  ++ "  else if x == 1 then .ok 20\n"
  ++ "  else .ok 30\n"

/-- Project an emission to its forward text (`""` on rejection, so a
    rejection also fails the golden examples below). Top-level def so
    `native_decide` can compile it. -/
def emitForwardText : Except EmitError EmittedFunc → String
  | .ok e => e.forward
  | .error _ => ""

/-- File bytes for one emission: forward text plus the backward definition
    (if any). Top-level def so `native_decide` can compile it. -/
def emitFileText : Except EmitError EmittedFunc → String
  | .ok e =>
    match e.backward with
    | none => e.forward
    | some b => e.forward ++ "\n" ++ b
  | .error _ => ""
